/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html", "./js/**/*.js"],
  theme: {
    extend: {
      fontFamily: {
        lexend: ["Lexend", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        "label-md": ["Hanken Grotesk"],
        "headline-xl": ["Lexend"],
        "headline-lg": ["Lexend"],
        "headline-sm": ["Lexend"],
        "body-sm": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "headline-md": ["Lexend"],
        "headline-lg-mobile": ["Lexend"],
      },
      colors: {
        "emerald-accent": "#10b981",
        "brand-green": "#10b981",
        "dark-bg": "#000000",
        "sidebar-bg": "#0f172a",
        "card-bg": "#000000",
        "border-subtle": "#333333",
        "fan-dark": "#060b13",
        "fan-card-bg": "rgba(16,24,39,0.6)",
        "fan-emerald": "#10b981",
        "fan-emerald-dark": "#059669",
        "fan-border": "rgba(255,255,255,0.1)",
        "surface-container-high": "#dce9ff",
        tertiary: "#545f73",
        surface: "#f8f9ff",
        "surface-container": "#e5eeff",
        "primary-fixed": "#6ffbbe",
        "outline-variant": "#bbcabf",
        "inverse-primary": "#4edea3",
        "secondary-fixed-dim": "#c0c1ff",
        "secondary-container": "#6063ee",
        outline: "#6c7a71",
        "inverse-surface": "#213145",
        "primary-container": "#10b981",
        "on-primary-fixed-variant": "#005236",
        "on-tertiary-fixed-variant": "#3c475a",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#bcc7de",
        "on-surface-variant": "#3c4a42",
        "secondary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#07006c",
        "surface-variant": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "on-surface": "#0b1c30",
        primary: "#006c49",
        "on-tertiary-fixed": "#111c2d",
        "on-tertiary-container": "#2e394c",
        "tertiary-fixed": "#d8e3fb",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary-container": "#fffbff",
        "on-primary-container": "#00422b",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-background": "#0b1c30",
        "surface-tint": "#006c49",
        "primary-fixed-dim": "#4edea3",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#002113",
        "surface-container-highest": "#d3e4fe",
        error: "#ba1a1a",
        secondary: "#4648d4",
        "surface-bright": "#f8f9ff",
        background: "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "tertiary-container": "#98a3ba",
        "on-secondary": "#ffffff",
        brand: {
          green: "#10b981",
          dark: "#0B0E11",
          blue: "#4154F1",
          card: "#16191E",
          secondary: "#1A213E",
          border: "rgba(255,255,255,0.1)",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        "max-width": "1440px",
        "margin-desktop": "32px",
        gutter: "24px",
        xl: "64px",
        sm: "12px",
        lg: "40px",
        md: "24px",
        "margin-mobile": "16px",
        base: "8px",
      },
      fontSize: {
        "label-md": [
          "14px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "headline-xl": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
